# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# シェルのプロンプトの間に空行を挿入する
add_newline = true

# 記号"❯"を記号"➜"に置き換える
[character] # 設定対象のモジュール名は 'character'
success_symbol = '[➜](bold green)' # セグメント 'success_symbol' を '$' 配色 'bold green' (太字の緑色) に設定

# package モジュールを無効化してプロンプトから完全に非表示にする
[package]
disabled = true

# バッテリー
[[battery.display]] # バッテリー容量が0～10%の時'bold red'(太字の赤)でdischarging_symbolを表示
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

# メモリ
[memory_usage]
threshold = -1
disabled = false

# mise
[mise]
healthy_symbol = 'ready'
disabled = false

# 時計
[time]
disabled = false
format = "[$time]($style) "
style = "bold blue"